### PR TITLE
Set explicitly the type `button` for buttons.

### PR DESCRIPTION
**Pull request by iamdey**
When the editor is in a `form` the search buttons will submit the form.

### CODE REVIEW

**Comment by marijnh** [comment]
Good idea. There's also the close button, which isn't created through the `button` function.

And don't put your release note in the changelog—put it in a `FIX: ...` line in the commit message.

**Comment by marijnh** [comment]
Thanks. Just one more nitpick: Please use double quoted strings.

**Comment by iamdey** [comment]
Woops I missed this close button. fixed.

---

Also is it possible to release a patch version for 0.18? 

The version 0.19 of codemirror works fine in the browser but for an obscure reason it makes the CI stuck in an infinite loop (jest + testing-library). I'll come with a more detailed investigation on your discuss website as soon as possible.

**Comment by marijnh** [comment]
Sorry, I'm not backporting changes to previous releases at this point.

**Pull request merged**
